name: Auth0 Deploy CLI
description: deploy or import using the Auth0 deploy-cli
author: Chris Scott

inputs:
  domain:
    description: Auth0 tenant domain
    required: true
  client_id:
    description: auth0-deploy-cli-extension client id
    required: true
  client_secret:
    description: auth0-deploy-cli-extension client secret
    required: true
  input_file:
    description: deploy-cli input file (yaml) or path (directory)
    required: true
  deploy_command:
    description: "deploy-cli command to run. One of: import, deploy, export, or dump."
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
