name: Auth0 Deploy CLI
description: deploy or import using the Auth0 deploy-cli
author: Chris Scott

inputs:
  deploy_command:
    description: "The deploy-cli command to run. One of: import, deploy, export, or dump."
    required: true
  input:
    description: Path to tenant.yaml or to a directory structure, depending on configuration.
    required: true
  format:
    description: "Output format: yaml or directory"
    required: true
  output:
    description: Output path for the export/dump command.
    required: false

runs:
  using: "node12"
  main: "dist/index.js"
